export enum CreditAuditLogType {
	CREDIT_AUTHORIZED = 'CREDIT_AUTHORIZED',
	CREDIT_ISSUED = 'CREDIT_ISSUED',
	CREDIT_RETIRED = 'CREDIT_RETIRED',
	CREDIT_CANCELLED = 'CREDIT_CANCELLED',
	CREDIT_ASSIGNED_TO_EXCHANGE = 'CREDIT_ASSIGNED_TO_EXCHANGE'
}
