export enum GovDepartment {
    "Department of Forestry" = "1",
    "Department of Environment" = "2",
    "Department of Agricultural Land Management" = "3",
    "Department of Livestock and Fisheries" = "4",
    "Department of Water Resources" = "5",
    "Department of Energy Policy and Planning" = "6",
    "Department of Energy Business" = "7",
    "Department of Mines" = "8",
    "Department of Industry" = "9",
    "Department of Domestic Trade" = "10",
    "Department of Foreign Trade Policy" = "11",
    "Department of Transport" = "12",
    "Department of Public Works" = "13",
    "Department of Housing and Urban Planning" = "14",
    "Department of Hygiene and Health Promotion" = "15",
    "Department of Healthcare and Rehabilitation" = "16",
    "Department of Higher Education" = "17",
    "Department of Technical and Vocational Education" = "18",
    "Other" = "19",
}
